app/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', home, name='index'),
    path('events/', EventListView.as_view(), name='event-list'),
    path('events/<int:pk>/', EventDetailView.as_view(), name='event-detail'),
    path('programs/', ProgramListView.as_view(), name='program-list'),
    path('programs/<int:pk>/', ProgramDetailView.as_view(), name='program-detail'),
    path('contact-us/', ContactUsView.as_view(), name='contact-us'),
    path('about-me/', AboutMeView.as_view(), name='about-me'),
    path('videos/', VideoView.as_view(), name='videos'),
]

app/models.py
from django.db import models


class Event(models.Model):
    event_name = models.CharField(max_length=100)
    banner_photo = models.ImageField(upload_to='event_photos/')
    heading_photo = models.ImageField(upload_to='event_photos/')
    description = models.TextField()
    other_photos = models.ManyToManyField('Photos', related_name='event_photos', null=True, blank=True)
    youtube_video_url = models.ManyToManyField('MediaUrls', related_name='event_links', blank=True, null=True)
    video_file = models.FileField(upload_to='videos/')
    event_date = models.DateField()
    duration = models.CharField(help_text="Duration in hours", max_length=100)
    start_time = models.TimeField()
    end_time = models.TimeField()
    location = models.CharField(max_length=200)
    event_title = models.CharField(max_length=200)

    def __str__(self):
        return self.event_name + ' - ' + str(self.event_date)
    
class Program(models.Model):
    name = models.CharField(max_length=100)
    banner_photo = models.ImageField(upload_to='event_photos/')
    heading_photo = models.ImageField(upload_to='event_photos/')
    heading_text = models.CharField(max_length=100)
    description = models.TextField()
    other_photos = models.ManyToManyField('Photos', related_name='program_photos', null=True, blank=True)
    youtube_video_url = models.ManyToManyField('MediaUrls', related_name='programs_links', blank=True, null=True)

    def __str__(self):
        return self.name


class Photos(models.Model):
    photo = models.ImageField(upload_to='event_photos/')

    def __str__(self):
        return self.photo.url
    

class MediaUrls(models.Model):
    url = models.URLField()


class YoutubeUrls(models.Model):
    url = models.URLField()


class NewTable(models.Model):
    name = models.CharField(max_length=100)

app/templates/about_me.html
{% include 'header.html' %}
{% load static %}
	
	<div class="page-content bg-white">
		
		<!-- Banner  -->
		<div class="dz-bnr-inr style-2" style="background-image: url('{% static 'images/main_banner.jpg' %}')">
			<div class="banner-gradient"></div>
			<div class="container">
				<div class="row">
					<div class="col-lg-8">
						<div class="dz-bnr-inr-entry">
							<h1>About Us</h1>
							<!-- Breadcrumb Row -->
							<nav aria-label="breadcrumb" class="breadcrumb-row">
								<ul class="breadcrumb">
									<li class="breadcrumb-item"><a href="/">Home</a></li>
									<li class="breadcrumb-item active" aria-current="page">About Us</li>
								</ul>
							</nav>
							<!-- Breadcrumb Row End -->
						</div>
					</div>
				</div>	
			</div>	
		</div>
		<!-- Banner End -->
		
		<section class=" membership-box-2 about-bx1">
			<div class="container">
				<div class="row ">
					<div class="col-lg-5 col-md-12 wow fadeInUp about-content" data-wow-delay="0.4s" style="visibility: visible; animation-delay: 0.4s; animation-name: fadeInUp;">
						<div class="about-content">	
							<h3 class="title text-white m-0">Pankaj Pasi<span class="text-primary"></span></h3>
						<p class="description text-white m-b40">founder of Strength bar athelete Vadodara first open air Calisthenics park.
							Working in Fitness Industry more than 10 years. His goal is to help people
							cultivate long-term Fitness and happiness through creating Fitness content and building community.
						</p></div>
					</div>
				</div>
			</div>
				
		</section>
		<!-- About Us -->
		<section class="content-inner">
			<div class="container">
				<!-- About Services -->
				<div class="row about-bx1 align-items-center ">
					<div class="col-lg-6">
						<div class="dz-media p-r20">
							<div class="image-box wow fadeInUp" data-wow-delay="0.4s">
								<div class="tag"><h2 class="counter">10</h2><h5>year experience</h5></div>
								<div class="split-box h-100">
									<video autoplay loop muted id="about-video">
										<source src="{% static 'media/video1.mp4' %}" type="video/mp4">
									</video>
								</div>
							</div>
							<div class="split-box">
								<img src="{% static 'images/img1_copy.jpg' %}" alt="" class="wow fadeInUp" data-wow-delay="0.6s">
							</div>
						</div>
					</div>
					<div class="col-lg-6 about-content m-lg-t40 wow fadeInUp" data-wow-delay="0.6s">
						<h3 class="sub-title wow fadeInUp" data-wow-delay="0.8s">WAKE UP IT’S TIME</h3>
						<h2 class="title m-0 wow fadeInUp" data-wow-delay="1.0s">To Take The <span class="text-primary">Action</span></h2>
						<p class="description m-b10 wow fadeInUp" data-wow-delay="1.2s">Ready to unlock your full potential ?</p>
						<p class="wow fadeInUp" data-wow-delay="1.4s">Whether you're looking to build muscle, improve endurance, or simply lead a healthier lifestyle, together, we'll create a personalized training program tailored to your needs and aspirations.</p>
						<ul class="pr-list list-italic m-t30 m-b35 wow fadeInUp" data-wow-delay="1.6s">
							<li><i class="flaticon-check-mark"></i>Calisthenics</li>
							<li><i class="flaticon-check-mark"></i>Functional Training</li>
							<li><i class="flaticon-check-mark"></i>Mobility & Flexibility</li>
							<li><i class="flaticon-check-mark"></i>Skill & Tricks </li>
							<li><i class="flaticon-check-mark"></i>Body Building</li>
						</ul>
						<div class="wow fadeInUp" data-wow-delay="1.8s">
							<a href="{% url 'contact-us' %}" class="btn btn-skew btn-lg btn-primary">
								<span class="skew-inner">
									<span class="text">Get Started</span>
								</span>
							</a>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- About Us -->
		
		<!-- Testimonials-->
		<section class="content-inner-3 testimonial-wrapper1">
			<div class="container">
				<div class="section-head style-2 text-center">
					<h2 class="title m-b5 wow fadeInUp" data-wow-delay="0.4s">Testimonials</h2>
				</div>
			</div>
			<div class="swiper testimonial-swiper-1">
				<div class="swiper-wrapper">
					<div class="swiper-slide wow fadeInUp" data-wow-delay="0.2s">
						<div class="testimonial-1">
							<div class="testimonial-info">
								<i class="quotes-icon flaticon-quote"></i>
								<div class="testimonial-text m-sm-b20 m-b30">
									<p>One of the best thing happening in Vadodara “SBA CALISTHENICS PARK“.
										I’m never doing any skill related workouts and then I’m starting my calisthenics journey with SBA.
										I have joined SBA one month back and I noticed changes in my body. Pankaj sir specially attention to everybody in group training with friendly nature.
										Amazing place to learn Calisthenics.</p>
								</div>
							</div>
							<div class="testimonial-details">
								<div class="d-flex align-items-center">
									<div class="info">
										<h4 class="testimonial-name">Bhavik Mahant</h4> 
									</div>
								</div>
								<ul class="testimonial-rating">
									<li><i class="fa-solid fa-star"></i></li>
									<li><i class="fa-solid fa-star"></i></li>
									<li><i class="fa-solid fa-star"></i></li>
									<li><i class="fa-solid fa-star"></i></li>
									<li><i class="fa-solid fa-star"></i></li>
								</ul>
							</div>
						</div>
					</div>
					<div class="swiper-slide wow fadeInUp" data-wow-delay="0.4s">
						<div class="testimonial-1">
							<div class="testimonial-info">
								<i class="quotes-icon flaticon-quote"></i>
								<div class="testimonial-text m-sm-b20 m-b30">
									<p> Pankaj sir brings an impressive concept of an outdoor workout (Calisthenics) during sunrise and sunset hours. To all the females out there, it is a super fun strength building concept for all of you.
										Our trainer-Pankaj sir, is extremely dedicated and committed, keeps himself updated practically as well as theoretically. He personally monitors, trains and pushes us to new limits each week by bringing in new concepts of training.
										Highly recommended
										</p>
								</div>
							</div>
							<div class="testimonial-details">
								<div class="d-flex align-items-center">
									<div class="info">
										<h4 class="testimonial-name">Janhvi Shah</h4> 
									</div>
								</div>
								<ul class="testimonial-rating">
									<li><i class="fa-solid fa-star"></i></li>
									<li><i class="fa-solid fa-star"></i></li>
									<li><i class="fa-solid fa-star"></i></li>
									<li><i class="fa-solid fa-star"></i></li>
									<li><i class="fa-solid fa-star"></i></li>
								</ul>
							</div>
						</div>
					</div>
					<div class="swiper-slide wow fadeInUp" data-wow-delay="0.8s">
						<div class="testimonial-1">
							<div class="testimonial-info">
								<i class="quotes-icon flaticon-quote"></i>
								<div class="testimonial-text m-sm-b20 m-b30">
									<p>I am associated with him last 4 months. And I have lost 10 kg in 110 days. Earlier I could barely do 2-3 push-ups, 
										now I can do 20-25. And I am also learning calisthenics. Now I can also do things like elbow lever, frog stand with ease.
										Pankaj Pasi sir is a very good coach for calisthenics. Before this, I had changed 2 gyms but it did not make any difference in my weight loss, 
										I was able to do this with sir's diet and exercise.</p>
								</div>
							</div>
							<div class="testimonial-details">
								<div class="d-flex align-items-center">
									<div class="info">
										<h4 class="testimonial-name">Aryan Dave</h4> 
									</div>
								</div>
								<ul class="testimonial-rating">
									<li><i class="fa-solid fa-star"></i></li>
									<li><i class="fa-solid fa-star"></i></li>
									<li><i class="fa-solid fa-star"></i></li>
									<li><i class="fa-solid fa-star"></i></li>
									<li><i class="fa-solid fa-star"></i></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="clearfix justify-content-center d-flex m-sm-t30 m-t50">
					<div class="num-pagination">
						<div class="swiper-pagination dz-swiper-pagination1 style-2 justify-content-center"></div>
					</div>
				</div>
			</div>
		</section>
		<!-- Testimonials-->
		
	</div>

{% include 'footer.html' %}

app/templates/contact_us.html
{% include 'header.html' %}
{% load static %}

<div class="page-content bg-white">
		
	<!--banner-->
	<div class="contact-bnr" style="background-image: url({% static 'images/bg9.png' %});">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">

					<div class="contact-info style-1 text-start text-white">
						<h2 class="title wow fadeInUp" data-wow-delay="0.1s">DISCOVER US</h2>
						<p class="text wow fadeInUp" data-wow-delay="0.2s"><span class="text-decoration-underline text-white"><a class="text-white" href="javascript:void(0)">Pankaj Pasi is here to help you;</a></span> <br> He is available to answer any questions you might have.</p>
						<div class="contact-bottom wow fadeInUp" data-wow-delay="0.3s">
							<div class="contact-left">
								<h3>Call Us</h3>
								<ul>
									<li><a href="tel:+917048660327">+91704 866 0327</a></li>
									<li><a href="tel:+918160964128">+91816 096 4128</a></li>
								</ul>
							</div>
							<div class="contact-right">
								<h3>Email Us </h3>
								<ul> 
									<li>calitalks.in@gmail.com</li>
								</ul>
							</div>		
						</div>
					</div>
				</div>
				<!-- your_template.html -->
				<div class="col-lg-6">
					<div class="contact-area1 style-1 m-r20 m-md-r0 wow fadeInUp" data-wow-delay="0.5s">
						{% if form.is_valid %}
						<div class="alert alert-success" role="alert">
							Your message has been sent successfully!
						</div>
						{% endif %}
						<form class="dz-form" method="POST" id="contactForm" action="{% url 'contact-us' %}">
							{% csrf_token %}
							<input type="hidden" class="form-control" name="dzToDo" value="Contact">
							<input type="hidden" class="form-control" name="reCaptchaEnable" value="0">
							<div class="dzFormMsg"></div>
							<label class="form-label">Your Name</label>
							<div class="input-group">
								{{ form.name }}
							</div>
							{% if form.name.errors %}
								<span class="text-danger">{{ form.name.errors }}</span>
							{% endif %}
							<label class="form-label">Email Address</label>
							<div class="input-group">
								{{ form.email }}
							</div>
							{% if form.email.errors %}
								<span class="text-danger">{{ form.email.errors }}</span>
							{% endif %}
							<label class="form-label">Phone Number</label>
							<div class="input-group">
								{{ form.phone_number }}
							</div>
							{% if form.phone_number.errors %}
								<span class="text-danger">{{ form.phone_number.errors }}</span>
							{% endif %}
							<label class="form-label">Message</label>
							<div class="input-group m-b30">
								{{ form.message }}
							</div>
							{% if form.message.errors %}
								<span class="text-danger">{{ form.message.errors }}</span>
							{% endif %}
							<div>
								<button name="contactformsubit" type="submit" value="submit" class="btn btn-primary w-100">SUBMIT</button>
							</div>
						</form>
					</div>
				</div>

			</div>
		</div>
	</div>
</div>

{% include 'footer.html' %}

app/templates/event_detail.html
{% include 'header.html' %}
{% load static %}
	
	<div class="page-content bg-white">
		<!-- Our Event Detail -->
		<section class="content-inner">
			<div class="container">
				<div class="row">
					<div class="col-lg-8">
						<div class="event-single">
							<div class="dz-media wow fadeInUp" data-wow-delay="0.4s">
								<img src="{{ current_event.banner_photo.url }}" alt="/">
							</div>
							<div class="dz-info">
								<h1 class="dz-title wow fadeInUp" data-wow-delay="0.6s">{{ current_event.event_name }}</h1>
									{{ current_event.description|safe }}

							</div>
							<section class="gallery">
								<div class="row">
									{% for image in current_event.other_photos.all %}
									<div class="col-xl-6 col-lg-6">
										<div class="fluid-container">
											<div class="item">
												<div class="img">
													<img src="{{ image.photo.url}}">
												</div>
												<div class="info"><span class="title"></span>
												</div>
											</div>
										</div>
									</div>
									{% endfor %}
								</div>
							</section>
							<div class="overlay">
								<div class="viewer">
									<div>
										<div class="alt">this image is ... </div>
										<button class="close"><span class="material-symbols-rounded">close</span></button>
									</div>
									<div><img></div>
								</div>
							</div>
							{% if current_event.youtube_video_url.all %}
							<!-- <p> exists {{current_event.youtube_video_url.all}} </p> -->
							<div class="dz-media">
									{% for youtube_video in current_event.youtube_video_url.all %}
										<iframe width="100%" height="315" src="{{ youtube_video.url }}" frameborder="0" allowfullscreen></iframe>
									{% endfor %}
							</div>
							{% endif %}
							{% if current_event.video_file %}
							<div class="video-container">
								<video controls>
									<source src="{{ current_event.video_file.url }}" type="video/mp4">
									Your browser does not support the video tag.
								</video>
							</div>
							{% endif %}
						</div>
					</div>
					<div class="col-lg-4 ">
						<aside class="side-bar sticky-top">
							<h3 class="sidebar-title wow fadeInUp" data-wow-delay="0.4s">Event Details</h3>
							<div class="cart-sidebar">
								<div class="cart-detail m-b30 wow fadeInUp" data-wow-delay="0.6s">
									<table>
										<tbody>
											<tr>
												<td>
													<h6 class="mb-0">Date</h6>
												</td>
												<td class="price">
													{{ current_event.event_date|date:"d F Y" }}
												</td>
											</tr>
											<tr>
												<td>
													<h6 class="mb-0">Event Title</h6>
												</td>
												<td class="price">
													{{ current_event.event_title }}
												</td>
											</tr>
											<tr>
												<td>
													<h6 class="mb-0">Duration</h6>
												</td>
												<td class="price">
													{{ current_event.duration }}
												</td>
											</tr>
											<tr>
												<td>
													<h6 class="mb-0">Time</h6>
												</td>
												<td class="price">
													{{ current_event.start_time|time:"h:i A" }} - {{ current_event.end_time|time:"h:i A" }}
												</td>
											</tr>
											<tr>
												<td>
													<h6 class="mb-0">Location</h6>
												</td>
												<td class="price">
													{{ current_event.location }}
												</td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
						</aside>
					</div>
				</div>
			</div>
		</section>
		<div class="content-inner pt-0">
			<div class="container">
				<div class="row">
					{% for event in event_list %}
					<h4 class="title font-weight-700 m-b30">Related Events</h4>

					<div class="col-xl-6 col-lg-8">
						<div class="dz-card style-1 blog-half m-b30 overlay-shine wow fadeInUp" data-wow-delay="0.1s">
							<div class="dz-media">
								<a><img src="{{ current_event.heading_photo.url }}" alt="/"></a>
							</div>
							<div class="dz-info">
								<div class="dz-meta">
									<ul>
										<li class="dz-date">
											<span>{{ event.event_date|date:"d" }}</span> {{ event.event_date|date:"M" }}
										</li>
										<li class="dz-time">
											<a> {{ event.start_time|time:"h:i A" }} - {{ event.end_time|time:"h:i A" }} </a>
										</li>
									</ul>
								</div> 
								<h4 class="dz-title"><a href="{% url 'event-detail' pk=event.pk %}">{{ event.name}}</a></h4>
								<p> {{ event.description |truncatechars:80}} </p>
								<a class="read-btn btn-link" href="{% url 'event-detail' pk=event.pk %}">Read More</a>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
		<!-- Our Event Detail -->
	
{% include 'footer.html' %}

app/templates/events.html
{% include 'header.html' %}
{% load static %}
	
	<div class="page-content bg-white">
		
		<!-- Banner  -->
		<div class="dz-bnr-inr style-2" style="background-image: url({% static 'images/main_banner.jpg' %})">
			<div class="banner-gradient"></div>
			<div class="container">
				<div class="row">
					<div class="col-lg-8">
						<div class="dz-bnr-inr-entry">
							<h1>Events</h1>
							<!-- Breadcrumb Row -->
							<nav aria-label="breadcrumb" class="breadcrumb-row">
								<ul class="breadcrumb">
									<li class="breadcrumb-item"><a href="/">Home</a></li>
									<li class="breadcrumb-item active"><a href="{{ view_url }}"></a>Events</li>
								</ul>
							</nav>
							<!-- Breadcrumb Row End -->
						</div>
					</div>
				</div>	
			</div>	
		</div>
		<!-- Banner End -->
		
		<!-- Our Events -->
		<section class="content-inner">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="row justify-content-center">
							{% for event in events %}
							<div class="col-xl-6 col-lg-8">
								<div class="dz-card style-1 blog-half m-b30 overlay-shine wow fadeInUp" data-wow-delay="0.1s">
									<div class="dz-media">
										<a><img src="{{ event.heading_photo.url }}" alt="/"></a>
									</div>
									<div class="dz-info">
										<div class="dz-meta">
											<ul>
												<li class="dz-date">
													<span>{{ event.event_date|date:"d" }}</span> {{ event.event_date|date:"M" }}
												</li>
												<li class="dz-time">
													<a> {{ event.start_time|time:"h:i A" }} - {{ event.end_time|time:"h:i A" }} </a>
												</li>
											</ul>
										</div> 
										<h4 class="dz-title"><a href="{% url 'event-detail' pk=event.pk %}">{{ event.name}}</a></h4>
										<p> {{ event.description |truncatechars:80|safe}} </p>
										<a class="read-btn btn-link" href="{% url 'event-detail' pk=event.pk %}">Read More</a>
									</div>
								</div>
							</div>
							{% endfor %}
						</div>
						<div class="col-lg-12 m-b50">
							<nav>
								<ul class="pagination pagination-gutter pagination-primary no-bg m-b15">
									{% if page_obj.has_previous %}
										<li class="page-item"><a class="page-link prev" href="?page=1">First</a></li>
										<li class="page-item"><a class="page-link prev" href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
									{% endif %}
									{% for num in page_obj.paginator.page_range %}
										{% if num == page_obj.number %}
											<li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
										{% elif num in page_obj.paginator.page_range|slice:":3" or num in page_obj.paginator.page_range|slice:"-3:" %}
											<li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
										{% endif %}
									{% endfor %}
									{% if page_obj.has_next %}
										<li class="page-item"><a class="page-link next" href="?page={{ page_obj.next_page_number }}">Next</a></li>
										<li class="page-item"><a class="page-link next" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
									{% endif %}
								</ul>
							</nav>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- Our Events -->

		{% include 'footer.html' %}

app/templates/footer.html
{% load static %}
<!-- Footer -->
<footer class="site-footer style-1 bg-parallax" style="background-image: url({% static 'images/footer-bg-2.jpg' %});" id="footer">
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-xl-3 col-md-12 wow fadeInUp" data-wow-delay="0.2s">
                    <div class="widget widget_about">
                        <div class="footer-logo logo-white">
                        </div>
                        <p>A Wonderful Serenity Has Taken Possession Of My Entire Soul, Like These.</p>
                        <span class="m-b15 d-block text-white font-weight-600">Our Socials</span>
                        <div class="dz-social-icon style-1 dz-hover-move dark">
                            <ul>									
                                <li>
                                    <a target="_blank" href="https://www.facebook.com/pankaj.pasi.750">
                                        <i class="fab fa-facebook-f"></i>
                                    </a>
                                </li>
                                <li>
                                    <a target="_blank" href="https://www.instagram.com/calitalks.in/">
                                        <i class="fab fa-instagram"></i>
                                    </a>
                                </li>
                                <li>
                                    <a target="_blank" href="https://www.youtube.com/@Calitalks">
                                        <i class="fab fa-youtube"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>							
                    </div>
                </div>
                <div class="col-xl-3 col-md-4 wow fadeInUp" data-wow-delay="0.8s">
                    <div class="widget widget_working">
                        <h4 class="footer-title">Working Hours</h4>
                        <ul>
                            <li>
                                <span class="days">Monday – Saturday:</span>
                                <span class="time"> 05:00 – 21:00</a></span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer Bottom Part -->
    <div class="container">
        <div class="footer-bottom">
            <div class="text-center"> 
                <span>Copyright © <span class="current-year">2024</span>. All rights reserved.</span> 
            </div>
        </div>
    </div>
</footer>
<!-- Footer End -->

<div class="scroltop-progress scroltop-primary active-progress">
    <svg width="100%" height="100%" viewBox="-1 -1 102 102">
        <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98" style="transition: stroke-dashoffset 10ms linear 0s; stroke-dasharray: 307.919, 307.919; stroke-dashoffset: 24.3299px;"></path>
    </svg>
</div>
</div>
<!-- JAVASCRIPT FILES ========================================= -->
<script src="{% static 'js/jquery.min.js' %}"></script><!-- JQUERY.MIN JS -->
<script src="{% static 'js/wow.js' %}"></script><!-- WOW.JS -->
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script><!-- BOOTSTRAP.MIN JS -->
<script src="{% static 'js/splitting.min.js' %}"></script><!-- Splitting -->
<script src="{% static 'js/bootstrap-select.min.js' %}"></script><!-- BOOTSTRAP SELEECT -->
<script src="{% static 'js/magnific-popup.js' %}"></script><!-- MAGNIFIC POPUP JS -->
<script src="{% static 'js/waypoints-min.js' %}"></script><!-- WAYPOINTS JS -->
<script src="{% static 'js/counterup.min.js' %}"></script><!-- COUNTERUP JS -->
<script src="{% static 'js/swiper-bundle.min.js' %}"></script><!-- SWIPER -->
<script src="{% static 'js/rangeslider.js' %}"></script><!-- RANGESLIDER -->
<script src="{% static 'js/switcher.js' %}"></script><!-- SWITCHER -->
<script src="{% static 'js/dz.carousel.js' %}"></script><!-- OWL-CAROUSEL -->
<script src="{% static 'js/dz.ajax.js' %}"></script><!-- AJAX -->
<script src="{% static 'js/custom.js' %}"></script><!-- CUSTOM JS -->
<script src="{% static 'js/imagesloaded.js' %}"></script><!-- IMAGESLOADED -->
<script src="{% static 'js/masonry-4.2.2.js' %}"></script><!-- MASONRY -->
<script src="{% static 'js/isotope.pkgd.min.js' %}"></script><!-- MASONRY -->
<script src="{% static 'js/lightgallery.min.js' %}"></script>
<script src="{% static 'js/lg-thumbnail.min.js' %}"></script>
<script src="{% static 'js/lg-zoom.min.js' %}"></script>
<script src="{% static 'js/test_js.js' %}"></script>


</body></html>

app/templates/video.html
{% include 'header.html' %}
{% load static %}
	
	<div class="page-content bg-white">
		
		<!-- Banner  -->
		<div class="dz-bnr-inr style-2" style="background-image: url({% static 'images/main_banner.jpg' %})">
			<div class="banner-gradient"></div>
			<div class="container">
				<div class="row">
					<div class="col-lg-8">
						<div class="dz-bnr-inr-entry">
							<h1>Videos</h1>
							<!-- Breadcrumb Row -->
							<nav aria-label="breadcrumb" class="breadcrumb-row">
								<ul class="breadcrumb">
									<li class="breadcrumb-item"><a href="/">Home</a></li>
									<li class="breadcrumb-item active"><a href="{{ view_url }}"></a>Videos</li>
								</ul>
							</nav>
							<!-- Breadcrumb Row End -->
						</div>
					</div>
				</div>
			</div>	
		</div>
		<!-- Banner End -->
		
		<!-- Our Events -->
		<section class="content-inner">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="row justify-content-center">
							{% for video in videos %}
							<div class="col-xl-6 col-lg-8">
								<div class="dz-media">
									<iframe width="100%" height="315" src="{{ video.url }}" frameborder="0" allowfullscreen></iframe>
								</div>
							</div>
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- Our Events -->

		{% include 'footer.html' %}